In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df=pd.read_csv("E:/Data Science/kaggle/kaggle-data/digit-recognizer/train.csv")

In [3]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.describe()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,42000.000000,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,...,42000.000000,42000.000000,42000.000000,42000.00000,42000.000000,42000.000000,42000.0,42000.0,42000.0,42000.0
mean,4.456643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.219286,0.117095,0.059024,0.02019,0.017238,0.002857,0.0,0.0,0.0,0.0
std,2.887730,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.312890,4.633819,3.274488,1.75987,1.894498,0.414264,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,254.000000,254.000000,253.000000,253.00000,254.000000,62.000000,0.0,0.0,0.0,0.0

In [5]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

Using TensorFlow backend.

In [6]:
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [7]:
features=df.loc[:,df.columns!='label']
labels=df['label']

In [8]:
X_train,X_test,y_train,y_test=train_test_split(features,labels,test_size=0.1)

In [9]:
X_train = X_train.values.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.values.reshape(X_test.shape[0], 28, 28, 1)
X_train.shape

(37800, 28, 28, 1)

In [10]:
num_classes=10

In [11]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [12]:
y_train.shape

(37800, 10)

In [13]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(28,28,1)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

WARNING:tensorflow:From C:\Users\Saurabh\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Saurabh\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.

In [14]:
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 64)        18496
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 64)        0
_________________________________________________________________
dropout_1 (Dropout)          (None, 12, 12, 64)        0
_________________________________________________________________
flatten_1 (Flatten)          (None, 9216)              0
_________________________________________________________________
dense_1 (Dense)              (None, 128)               1179776
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1290
=================================================================
Total params: 1,199,882
Trainable params: 1,199,882
Non-trainable params: 0
_________________________________________________________________

In [15]:
model.fit(X_train, y_train,
          batch_size=128,
          epochs=20,
          verbose=1,
          validation_data=(X_test, y_test))

WARNING:tensorflow:From C:\Users\Saurabh\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Train on 37800 samples, validate on 4200 samples
Epoch 1/20
37800/37800 [==============================] - 65s 2ms/step - loss: 2.1227 - acc: 0.8046 - val_loss: 0.1355 - val_acc: 0.9624
Epoch 2/20
37800/37800 [==============================] - 30s 795us/step - loss: 0.1464 - acc: 0.9586 - val_loss: 0.0724 - val_acc: 0.9798
Epoch 3/20
37800/37800 [==============================] - 37s 980us/step - loss: 0.1010 - acc: 0.9701 - val_loss: 0.0608 - val_acc: 0.9812
Epoch 4/20
37800/37800 [==============================] - 45s 1ms/step - loss: 0.0763 - acc: 0.9775 - val_loss: 0.0604 - val_acc: 0.9850
Epoch 5/20
37800/37800 [==============================] - 61s 2ms/step - loss: 0.0651 - acc: 0.9798 - val_loss: 0.0509 - val_acc: 0.9876
Epoch 6/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0560 - acc: 0.9836 - val_loss: 0.0485 - val_acc: 0.9886
Epoch 7/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0496 - acc: 0.9844 - val_loss: 0.0563 - val_acc: 0.9883
Epoch 8/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0410 - acc: 0.9879 - val_loss: 0.0482 - val_acc: 0.9886
Epoch 9/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0382 - acc: 0.9887 - val_loss: 0.0502 - val_acc: 0.9890
Epoch 10/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0353 - acc: 0.9889 - val_loss: 0.0479 - val_acc: 0.9886
Epoch 11/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0307 - acc: 0.9906 - val_loss: 0.0470 - val_acc: 0.9881
Epoch 12/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0276 - acc: 0.9911 - val_loss: 0.0523 - val_acc: 0.9871
Epoch 13/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0248 - acc: 0.9922 - val_loss: 0.0499 - val_acc: 0.9900
Epoch 14/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0246 - acc: 0.9926 - val_loss: 0.0543 - val_acc: 0.9905
Epoch 15/20
37800/37800 [==============================] - 66s 2ms/step - loss: 0.0222 - acc: 0.9933 - val_loss: 0.0456 - val_acc: 0.9898
Epoch 16/20
37800/37800 [==============================] - 66s 2ms/step - loss: 0.0234 - acc: 0.9926 - val_loss: 0.0427 - val_acc: 0.9912
Epoch 17/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0193 - acc: 0.9940 - val_loss: 0.0553 - val_acc: 0.9886
Epoch 18/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0183 - acc: 0.9940 - val_loss: 0.0426 - val_acc: 0.9902
Epoch 19/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0160 - acc: 0.9948 - val_loss: 0.0507 - val_acc: 0.9898
Epoch 20/20
37800/37800 [==============================] - 65s 2ms/step - loss: 0.0175 - acc: 0.9949 - val_loss: 0.0483 - val_acc: 0.9883

In [16]:
test_df=pd.read_csv("E:/Data Science/kaggle/kaggle-data/digit-recognizer/test.csv")

In [17]:
preds=model.predict(test_df.values.reshape(test_df.shape[0],28,28,1))
preds=np.argmax(preds,axis=1)
preds

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [18]:
pd.DataFrame(preds,columns=['Label']).to_csv("output.csv")